
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.

stages:

  DB rollbackOneUpdate:
    actions:
      - type: liquibase
        if: "${LBCOMMAND} == rollbackOneUpdateSql"
        command: rollbackOneUpdateSql
        cmdArgs: { force: "true" }
      - type: liquibase
        if: "${LBCOMMAND} == rollbackOneUpdate"
        command: rollbackOneUpdate
        cmdArgs: { force: "true" }
