
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.
stages:

  DB rollbackOneChangeset:
    actions:
      - type: liquibase
        command: rollbackOneChangeset
        cmdArgs: { force: "true" }
